apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-service
  namespace: food-ordering
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery-service
  template:
    metadata:
      labels:
        app: delivery-service
    spec:
      containers:
        - name: delivery-service
          image: delivery-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8085
          envFrom:
            - configMapRef:
                name: delivery-service-config
            - secretRef:
                name: delivery-service-secret
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8085
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8085
            initialDelaySeconds: 30
            periodSeconds: 15
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
