apiVersion: v1
kind: Service
metadata:
  name: delivery-service
  namespace: food-ordering
spec:
  type: ClusterIP
  selector:
    app: delivery-service
  ports:
    - port: 8085
      targetPort: 8085
