apiVersion: v1
kind: Secret
metadata:
  name: order-service-secret
  namespace: food-ordering
type: Opaque
data:
  DB_USER: Zm9vZG9yZGVy
  DB_PASSWORD: Zm9vZG9yZGVy
  JWT_SECRET: d0o3QUE2UkJxWXVhSzkzWDNoR1laZzR0bEFhTjIraXdxU1BrMnNrOWxGSFl2ZUt3U21BbWd2aWRINmZwb3R3Nw==
