apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  namespace: food-ordering
spec:
  type: ClusterIP
  selector:
    app: catalog-service
  ports:
    - port: 8082
      targetPort: 8082
